-- CreateTable
CREATE TABLE "GeckoPhoto" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "photoUrl" TEXT NOT NULL,
    "takenAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isMain" BOOLEAN NOT NULL DEFAULT false,
    "geckoId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "GeckoPhoto_geckoId_fkey" FOREIGN KEY ("geckoId") REFERENCES "Gecko" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
